[project]
name = "writebetter"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "keyring>=25.7.0",
    "pillow>=12.3.0",
    "pynput>=1.8.2",
    "pyperclip>=1.11.0",
    "pyside6>=6.11.2",
]

[dependency-groups]
dev = [
    "pyinstaller>=6.22.2",
]
